export const USER_REGISTER="USER_REGISTER"
export const SET_CART_ITEMS="SET_CART_ITEMS"
// PAGES /
export const OPEN_DESHBOARD_PAGE="OPEN_DESHBOARD_PAGE"
// MODALS 
export const EDIT_ORDER_LIMIT_MODAL="EDIT_ORDER_LIMIT_MODAL"
export const ADD_BANNER_MODAL="ADD_BANNER_MODAL"
export const ADD_PAGE_MODAL="ADD_PAGE_MODAL"
export const ADD_ADDON_MODAL="ADD_ADDON_MODAL"
export const ADD_CATEGORY_MODAL="ADD_CATEGORY_MODAL"
export const ADD_SUBCATEGORY_MODAL="ADD_SUBCATEGORY_MODAL"
export const ADD_FOOD_MODAL="ADD_FOOD_MODAL"
// DATA 
export const ADD_ORDER_LIMIT_DATA="ADD_ORDER_LIMIT_DATA"