export const GET_ALL_FOODITEM_REQUEST = "GET_ALL_FOODITEM_REQUEST";
export const GET_ALL_FOODITEM_SUCESS = "GET_ALL_FOODITEM_SUCESS";
export const GET_ALL_FOODITEM_FAIL = "GET_ALL_FOODITEM_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
