export const GET_SUBCATEGORY_REQUEST="GET_SUBCATEGORY_REQUEST"
export const GET_SUBCATEGORY_SUCCESS="GET_SUBCATEGORY_SUCCESS"
export const GET_SUBCATEGORY_FAIL="GET_SUBCATEGORY_FAIL"

export const CLEAR_ERROR="CLEAR_ERROR"